name: MakeNTU
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - blas=1.1=openblas
  - bzip2=1.0.6=1
  - dbus=1.10.22=0
  - expat=2.2.5=0
  - ffmpeg=3.2.4=3
  - fontconfig=2.13.0=0
  - freetype=2.8.1=0
  - giflib=5.1.4=0
  - graphite2=1.3.11=0
  - hdf5=1.10.1=2
  - icu=58.2=0
  - jasper=1.900.1=4
  - jpeg=9b=2
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libtiff=4.0.9=0
  - libuuid=1.0.3=1
  - libwebp=0.5.2=7
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - numpy=1.14.2=py36_blas_openblas_200
  - openblas=0.2.20=7
  - opencv=3.4.1=py36_blas_openblas_200
  - pcre=8.41=1
  - pixman=0.34.0=1
  - setuptools=38.5.1=py36_0
  - x264=20131217=3
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - ca-certificates=2017.08.26=h1d4fec5_0
  - cairo=1.14.12=h77bcde2_0
  - certifi=2018.1.18=py36_0
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - gunicorn=19.8.1=py36_0
  - harfbuzz=1.7.6=hc5b324e_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.1=h19d6760_4
  - ncurses=6.0=h9df7e31_2
  - openssl=1.0.2n=hb7f436b_0
  - pip=9.0.1=py36_5
  - pyserial=3.4=py36h08da44b_0
  - python=3.6.4=hc3d631a_3
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - sqlite=3.22.0=h1bed415_0
  - tk=8.6.7=hc745277_3
  - wheel=0.30.0=py36hfd4bba0_1
  - xz=5.2.3=h55aa19d_2
  - zlib=1.2.11=ha838bed_2
  - opencv3=3.1.0=py36_0
  - pip:
    - absl-py==0.1.11
    - astor==0.6.2
    - bleach==1.5.0
    - chardet==3.0.4
    - click==6.7
    - cycler==0.10.0
    - decorator==4.2.1
    - dill==0.2.7.1
    - fire==0.1.3
    - flask==0.12.2
    - gast==0.2.0
    - get==0.0.39
    - grpcio==1.10.0
    - h5py==2.7.1
    - html5lib==0.9999999
    - idna==2.6
    - itsdangerous==0.24
    - jinja2==2.10
    - keras==2.1.5
    - kiwisolver==1.0.1
    - markdown==2.6.11
    - markupsafe==1.0
    - matplotlib==2.2.2
    - msgpack==0.5.6
    - msgpack-numpy==0.4.3
    - networkx==2.1
    - pillow==5.0.0
    - post==0.0.26
    - protobuf==3.5.2.post1
    - public==0.0.65
    - pyparsing==2.2.0
    - python-dateutil==2.7.0
    - pytz==2018.3
    - pywavelets==0.5.2
    - pyyaml==3.12
    - pyzmq==17.0.0
    - query-string==0.0.28
    - request==0.0.26
    - requests==2.18.4
    - scikit-image==0.13.1
    - scikit-learn==0.19.1
    - scikit-video==1.1.10
    - scipy==1.0.0
    - six==1.11.0
    - sk-video==1.1.10
    - tabulate==0.8.2
    - tensorboard==1.6.0
    - tensorflow==1.6.0
    - tensorpack==0.8.3
    - termcolor==1.1.0
    - tqdm==4.19.8
    - urllib3==1.22
    - werkzeug==0.14.1
prefix: /tmp3/b03901014/miniconda3/envs/MakeNTU

